services:
  arcane:
    image: ghcr.io/getarcaneapp/manager:v2.7.0
    restart: unless-stopped
    env_file:
      - config.env
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane_data:/app/data
      - /srv/infra/stacks:/srv/infra/stacks
    networks:
      - reverse-proxy
    cgroup: host
    healthcheck:
      test: ["CMD", "./arcane", "health", "--timeout", "2s"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 15s

volumes:
  arcane_data:

networks:
  reverse-proxy:
    external: true